name: ClueScrolls
version: 0.0.5
main: me.Aisu.ClueScrolls.Main
description: Travel to a randomly given location and claim rewards
depend: [RewardPools]
author: Aisuboirad
commands:
  Clues:
     description: Gives you this help menu
  Clues Reload:
     description: Reloads the chance list
     permission: Clues_Manager.Reload
  Clues give:
     description: gives a clue scroll
     permission: Clues_Manager.Give