##################################################################################################
##¤════════════════════════════════════════════════════════════════════════════════════════════¤##
##║¤═══════════════════════════These are the customizable messages.═══════════════════════════¤║##
##║¤═════════════════════Use %Command% Where the command should be listed═════════════════════¤║##
##║¤══════════════These can be colourcoded using the colour codes &* listed here══════════════¤║##
##║¤═════════════════════════http://minecraft.tools/en/color-code.php═════════════════════════¤║##
##¤════════════════════════════════════════════════════════════════════════════════════════════¤##
##################################################################################################
##################################################################################################
##¤════════════════════════════════════════════════════════════════════════════════════════════¤##
##║¤═════════════════════════════These are the customizable Ranges═════════════════════════════¤##
##║¤═════════════════════Ranges are from X:0 Z:0 and out in all directions═════════════════════¤##
##¤════════════════════════════════════════════════════════════════════════════════════════════¤##
##################################################################################################
Ranges:
    BeginnerScroll: 25
    lvl1Scroll: 2500
    lvl2Scroll: 5000
    lvl3Scroll: 10000