name: ClueScrolls
version: '${project.version}'
main: me.Aisu.ClueScrolls.Main
api-version: 1.19
description: Travel to a randomly given location and claim rewards
depend: [ RewardManager ]
authors: [ Aisuboirad ]
commands:
  Clues:
     description: Gives you this help menu
  Clues Reload:
     description: Reloads the chance list
     permission: Clues_Manager.Reload
  Clues give:
     description: gives a clue scroll
     permission: Clues_Manager.Give